# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e58f68ee1978f914dfa95b5422722733a595d8f4a33daf011bde15b1394d4f529c9862518aaa395e0395130a10282efdb4c1b0e8eb86762a3ce6ea4f08e02dc

test:
  secret_key_base: f5da36ef6a87634ca291911fd24dc790f5a30ba07ba6dc3a9e9890e7323d6280e59cf7f31de127c7df15215abff8019dad5245dd2f88e76f2b08bec5133b5b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
